apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: test4
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-e3731d11-d4e2-47cf-b07c-8e42bd131b31
      eventName: github-e3731d11-d4e2-47cf-b07c-8e42bd131b31
      eventSourceName: test4
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: push
        conditions: github-e3731d11-d4e2-47cf-b07c-8e42bd131b31
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: test4-push-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                workflowTemplateRef:
                  name: argo-hub.ci-simple.0.0.1
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-e3731d11-d4e2-47cf-b07c-8e42bd131b31
                dataTemplate: https://github.com/codefresh-io/cli
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-e3731d11-d4e2-47cf-b07c-8e42bd131b31
                dataTemplate: quay.io/eti_zaguri/test
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-e3731d11-d4e2-47cf-b07c-8e42bd131b31
                dataTemplate: 1.7.9
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-e3731d11-d4e2-47cf-b07c-8e42bd131b31
                dataTemplate: master
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-e3731d11-d4e2-47cf-b07c-8e42bd131b31
                dataTemplate: master
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-e3731d11-d4e2-47cf-b07c-8e42bd131b31
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-e3731d11-d4e2-47cf-b07c-8e42bd131b31
                dataTemplate: '{{ .Input.body.head_commit.message }}'
