apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: test123
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-b4b8e7bb-3f1d-4777-be63-7eca35f87958
      eventName: github-b4b8e7bb-3f1d-4777-be63-7eca35f87958
      eventSourceName: test123
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.head_commit.message
            comparator: '='
            template: '{{ .Input }}'
            type: string
            value:
              - hello
  triggers:
    - template:
        name: push
        conditions: github-b4b8e7bb-3f1d-4777-be63-7eca35f87958
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: test123-push-
              spec:
                arguments:
                  parameters:
                    - name: message
                      value: ''
                workflowTemplateRef:
                  name: hello-world
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-b4b8e7bb-3f1d-4777-be63-7eca35f87958
                dataTemplate: hello
