apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: test2
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-38118791-42a7-457a-bef8-18a4764ebf1a
      eventName: github-38118791-42a7-457a-bef8-18a4764ebf1a
      eventSourceName: test2
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: t
        conditions: github-38118791-42a7-457a-bef8-18a4764ebf1a
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: test2-t-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: 'https://github.com/codefresh-io/cli'
                    - name: IMAGE_NAME
                      value: 'quay.io/eti_zaguri/test'
#                     - name: IMAGE_TAG
#                       value: ''
                    - name: GIT_REVISION
                      value: 'master'
#                     - name: GIT_BRANCH
#                       value: ''
#                     - name: GIT_COMMIT_URL
#                       value: ''
#                     - name: GIT_COMMIT_MESSAGE
#                       value: ''
#                     - name: DOCKERFILE
#                       value: ''
#                     - name: GIT_TOKEN_SECRET
#                       value: ''
#                     - name: CONTEXT
#                       value: ''
#                     - name: REGISTRY_CREDS_SECRET
#                       value: ''
#                     - name: DOCKER_CONFIG_SECRET
#                       value: ''
                workflowTemplateRef:
                  name: ci-simple
          parameters: []
