apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: test4
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-e3731d11-d4e2-47cf-b07c-8e42bd131b31:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - pipeline-flow-demo
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/test4/github-e3731d11-d4e2-47cf-b07c-8e42bd131b31
        url: https://eti-demo.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
