apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: test2
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-38118791-42a7-457a-bef8-18a4764ebf1a:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - pipeline-flow-demo
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/test2/github-38118791-42a7-457a-bef8-18a4764ebf1a
        url: https://eti-demo.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
