apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: tetsfgg
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-97c5c49c-bbcc-4444-8cd9-91e89c381b8e:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - pipeline-flow-demo
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/tetsfgg/github-97c5c49c-bbcc-4444-8cd9-91e89c381b8e
        url: https://eti-demo.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
